[tox]
envlist = py{310, 311, 312, 313}

[testenv]
passenv =
    HOME
    LD_LIBRARY_PATH
    DYLD_LIBRARY_PATH
deps =
    pytest>=9.0.3,<10
    black>=26.3.1,<27
    flake8>=7,<8
    pylint>=3,<4
commands =
    black --check rnp
    flake8 rnp
    pylint -E rnp
    pytest -v

[flake8]
max-line-length = 88
