import pytest
import rnp


@pytest.fixture
def rpgp():
    return rnp.Rnp()


@pytest.fixture
def key(rpgp):
    return rpgp.generate_eddsa_25519("25519-tweak@test", None)


def test_bits_tweak_requires_ecdh_curve25519(key):
    # the primary key of an Ed25519/X25519 keypair is EdDSA, not ECDH,
    # so both calls must fail on it
    assert key.alg() == "EDDSA"
    with pytest.raises(rnp.RnpException):
        key.bits_25519_tweaked()
    with pytest.raises(rnp.RnpException):
        key.bits_25519_tweak()


def test_bits_tweak_idempotence(rpgp, key):
    subkey = next(key.subkeys())
    assert subkey.alg() == "ECDH"
    assert subkey.curve() == "Curve25519"
    # keys generated by RNP are clamped at generation time
    assert subkey.bits_25519_tweaked()
    # tweaking is idempotent on an unprotected key
    subkey.bits_25519_tweak()
    assert subkey.bits_25519_tweaked()
    subkey.bits_25519_tweak()
    assert subkey.bits_25519_tweaked()

    # the key remains fully usable afterwards
    encrypted = rpgp.encrypt(rnp.Input.from_bytes(b"secret data"), key)
    assert rpgp.decrypt(rnp.Input.from_bytes(encrypted)) == b"secret data"


def test_bits_tweak_requires_unlocked_unprotected(rpgp):
    key = rpgp.generate_eddsa_25519("25519-protected@test", "hunter2")
    subkey = next(key.subkeys())
    assert subkey.is_protected()
    assert subkey.is_locked()

    # checking requires an unlocked secret key
    with pytest.raises(rnp.RnpException):
        subkey.bits_25519_tweaked()
    # tweaking requires an unprotected secret key
    with pytest.raises(rnp.RnpException):
        subkey.bits_25519_tweak()

    subkey.unlock("hunter2")
    assert not subkey.is_locked()
    # checking works once unlocked (key was clamped at generation time)
    assert subkey.bits_25519_tweaked()
    # but tweaking still requires an unprotected key
    with pytest.raises(rnp.RnpException):
        subkey.bits_25519_tweak()
