name: release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'
  push:
    tags: [ v* ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - run: poetry install

    - if: github.event_name == 'workflow_dispatch' && github.event.inputs.next_version != 'skip'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        poetry version ${{ github.event.inputs.next_version }}

    - run: poetry build

    - run: poetry publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.RNP_PYPI_API_TOKEN }}

    - if: github.event_name == 'workflow_dispatch' && github.event.inputs.next_version != 'skip'
      run: |
        git add pyproject.toml
        git commit -m "Bump version to ${{ github.event.inputs.next_version }}"
        git tag v${{ github.event.inputs.next_version }}
        git push
